version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10.3

    steps:
      - checkout

      - run:
          name: install
          command: npm i

      - run:
          name: run tests
          command: echo run test

      - run:
          name: run lint
          command: echo run lint
